name: Check WP Version

on:
  schedule:
    - cron: '0 2 5 * *'
  workflow_dispatch:

jobs:
  is-outdated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Check if WordPress is outdated
        uses: tarosky/farmhand-wp-action@v1
        with:
          assignees: fumikito
          label: wp-org
